Added gcd function
charlesriver456/osgood pull request #27
Opened 2023-07-26 23:33 UTC by rosgood98

2023-07-27 13:41 UTC, charlesriver456 approved these changes

2023-07-27 13:46 UTC, DamianB-BitFlipper requested changes

2023-07-27 13:46 UTC, DamianB-BitFlipper commented on tests/test_base.py
> +def test_gcd() -> None:
Please parameterise these tests.

2023-08-02 18:43 UTC, DamianB-BitFlipper approved these changes
lgtm

2023-08-03 03:34 UTC, merged